### ISSUE TITLE
Fehler bei Benutzereingabe

### ISSUE THREAD

**Issue by Selemba1000** [emign/engineEmi_Template#2]
Fehlercode:
```
20:14:20: Executing task 'openLocal'...


> Configure project :
Kotlin Multiplatform Projects are an experimental feature.

> Task :compileKotlinJvm UP-TO-DATE
> Task :genResources UP-TO-DATE
> Task :jvmProcessResources UP-TO-DATE
> Task :jvmMainClasses UP-TO-DATE

> Task :runJvmFirstThread
screenWidth: 1366, screenHeight: 768, winX=-1317, winY=-624
VI: native@0x7f5cb85e73d0, d: native@0x7f5cb863b960 (com.sun.jna.platform.unix.X11$Display@b86438bc), w: 0x1000001, glc: native@0x7f5cb85e7660
GL_VENDOR: Intel Open Source Technology Center
GL_VERSION: 3.0 Mesa 19.2.8
keysim: 0x41
OpenglAG: Created program BatchBuilder2D.NoPremultiplied.Tinted with id 1 because contextVersion: -1 != 0
0.01
OpenglAG: Created program BatchBuilder2D.Premultiplied.Tinted with id 4 because contextVersion: -1 != 0

> Task :runJvmFirstThread FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runJvmFirstThread'.
> Process 'command '/home/Selemba/InteliJ/ideaIC-2019.3.3/idea-IC-193.6494.35/jbr/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
4 actionable tasks: 1 executed, 3 up-to-date
20:14:28: Task execution finished 'openLocal'.

```
Der Code der Main.kt:
```
import com.soywiz.klock.TimeSpan
import com.soywiz.korev.Key
import com.soywiz.korge.tween.moveTo
import com.soywiz.korim.color.Colors
import com.soywiz.korma.interpolation.Easing
import kotlinx.coroutines.GlobalScope
import kotlinx.coroutines.*
import me.emig.engineEmi.*
import me.emig.engineEmi.input.Keyboard
import me.emig.engineEmi.screenElements.bodies.Image
import me.emig.engineEmi.screenElements.bodies.Rectangle
import org.jbox2d.common.Vec2
import org.jbox2d.dynamics.BodyType


/**
 * Das Default (und eigentlich immer) das einzige Engine-Objekt
 */
val engine = Engine()

/**
 * Startpunkt für alle Programme.
 * Hier werden u.a. [Ebody] und [CanvasElement] Objekte bei der [Engine] registriert.
 * Es gibt drei Bereiche:
 * init : Dieser Code-Block wird zur Konfiguration der Engine verwendet. Hier kann man z.B. die Höhe und Breite des Fensters festlegen.
 * Wenn man diesen Block leer lässt, werden Standard-Werte geladen
 * viewWillLoad: Dieser Code-Block wird NACH der Konfiguration aber VOR dem Aufbau des Views (der Anzeige) ausgeführt. Hier sollte man
 * seine Objekte bei der Engine registrieren
 * viewDidLoad: Dieser Code-Block wird NACH dem der View komplett aufgebaut wurde ausgeführt. Hier sollte man Code platzieren, der darauf
 * angewiesen ist, dass Objekte bereits fertig erstellt und registriert wurden. Dies trifft vor allem auf [Ebody] Objekte zu.
 */

var player = Image(x= -6,y = -2,bodyType = BodyType.DYNAMIC, imageFile = "gfx/bird.png", scale = 0.010f)
var boden = Rectangle(x = 0,y = -3,width = 500,height = 0.1,fillColor = Colors.RED, friction = 0.1f)


var fspeed:Float=4f
var speed:Float=4f
var sprintspeed:Float=7f
var bounce = false


suspend fun main() {
    engine.run {



        /**
         * Code um die Engine zu konfigurieren.
         */
        init {


        }

        /**
         * Code der VOR dem Aufbau des Views ausgeführt wird
         */
        viewWillLoad {
            engine.register(boden)
            engine.register(player)

            boden.fixture.userData = "ground"

        }

        /**
         * Code, der NACH dem Aufbau des Views ausgeführt wird
         */
        viewDidLoad {
            player.body.isFixedRotation=true

            GlobalScope.launch{
                while (true) {

                    var isGround = (player.body.m_contactList?.contact?.m_fixtureA?.userData=="ground"||player.body.m_contactList?.contact?.m_fixtureB?.userData=="ground")&& player.body.m_contactList?.contact!!.isTouching

                    if (Keyboard.isKeyDown(Key.LEFT_SHIFT)){fspeed=sprintspeed}
                    if (!Keyboard.isKeyDown(Key.LEFT_SHIFT)){fspeed=speed}
                    if (Keyboard.isKeyDown(Key.D)){player.body.applyForceToCenter(Vec2(x = fspeed,y = 0f))}
                    if (Keyboard.isKeyDown(Key.A)){player.body.applyForceToCenter(Vec2(x = -fspeed,y = 0f))}
                    if (!Keyboard.isKeyDown(Key.A))player.body.linearVelocity.x=player.body.linearVelocity.x/1.06f
                    if (!Keyboard.isKeyDown(Key.D))player.body.linearVelocity.x=player.body.linearVelocity.x/1.06f
                    if (Keyboard.isKeyDown(Key.SPACE)&&isGround && !bounce){player.body.applyForceToCenter(Vec2(x = 0f,y = 100f));bounce=true;delay(100)}

                    if (!Keyboard.isKeyDown(Key.SPACE)){
                        bounce = false
                    }

                    delay(16)
                }
            }

            GlobalScope.launch {
                while (true) {
                    if (player.body.position.x>(engine.camera.pos.x/-200)+7)engine.camera.moveTo(x = player.body.position.x*-200,y = 0,time = TimeSpan(1000.0),easing = Easing.SMOOTH)
                    if (player.body.position.x<(engine.camera.pos.x/-200)-7)engine.camera.moveTo(x = player.body.position.x*-200,y = 0,time = TimeSpan(1000.0),easing = Easing.SMOOTH)
                    delay(16)
                }
            }

        }

        start()
    }
}
```
Bei der ersten Benutzereingabe kommt der Fehlercode und das Fenster nimmt keine Eingaben mehr an. Die Engine läuft aber weiter und Physikobjekte bewegen sich auch weiter.

**Comment by emign** [comment]
Bitte auf Unix-Systemen mit `.gradlew runJvm` ausführen. `openLocal` verwendet einen performanteren nativen Zugriffsmodus auf die Hardware, der bei Unix/Linux nicht vollständig unterstützt wird.

**Comment by Selemba1000** [comment]
Immer noch ähnlicher Fehler:
```
20:56:31: Executing task 'runJvm'...


> Configure project :
Kotlin Multiplatform Projects are an experimental feature.

> Task :compileKotlinJvm
> Task :genResources UP-TO-DATE
> Task :jvmProcessResources UP-TO-DATE
> Task :jvmMainClasses

> Task :runJvm
screenWidth: 1366, screenHeight: 768, winX=-1317, winY=-624
VI: native@0x7f4f0c62d720, d: native@0x7f4f0c6081e0 (com.sun.jna.platform.unix.X11$Display@c61012f), w: 0x1000001, glc: native@0x7f4f0c62d9b0
GL_VENDOR: Intel Open Source Technology Center
GL_VERSION: 3.0 Mesa 19.2.8
keysim: 0x41
OpenglAG: Created program BatchBuilder2D.NoPremultiplied.Tinted with id 1 because contextVersion: -1 != 0
0.01
OpenglAG: Created program BatchBuilder2D.Premultiplied.Tinted with id 4 because contextVersion: -1 != 0

> Task :runJvm FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runJvm'.
> Process 'command '/home/Selemba/InteliJ/ideaIC-2019.3.3/idea-IC-193.6494.35/jbr/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
4 actionable tasks: 2 executed, 2 up-to-date
20:56:43: Task execution finished 'runJvm'.

```

**Comment by emign** [comment]
Es sind wohl auch java native access Komponenten hier beteiligt. Da werden wir mit Linux immer Probleme haben. Es gibt noch zwei Möglichkeiten:
1. `.gradlew runJvmOtherThread`
2. Evtl mal [adoptopenjdk](https://adoptopenjdk.net/releases.html) testen und diesen auch als JDK im Projekt einstellen
3. `.gradlew runNative` könnte noch eine Option sein.
Falls beides nicht hilft, dann bitte mal mit `--stacktrace` ausführen und Konsolelog schicken.
Sonst bliebe unter Linux nur das JS target

**Comment by Selemba1000** [comment]
Fehler bei runNative:
```
15:48:18: Executing task 'runNative'...


> Configure project :
Kotlin Multiplatform Projects are an experimental feature.

> Task :prepareKotlinNativeBootstrap
> Task :compileKotlinLinuxX64 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlinLinuxX64'.
> Could not resolve all files for configuration ':linuxX64CompileKlibraries'.
   > Could not resolve me.emig:engineEmi:0.36.
     Required by:
         project :
      > Unable to find a matching variant of me.emig:engineEmi:0.36:
          - Variant 'iosArm32-api' capability me.emig:engineEmi:0.36:
              - Incompatible attribute:
                  - Required org.jetbrains.kotlin.native.target 'linux_x64' and found incompatible value 'ios_arm32'.
              - Other attributes:
                  - Found org.gradle.status 'release' but wasn't required.
                  - Required org.gradle.usage 'kotlin-api' and found compatible value 'kotlin-api'.
                  - Required org.jetbrains.kotlin.platform.type 'native' and found compatible value 'native'.
          - Variant 'iosArm64-api' capability me.emig:engineEmi:0.36:
              - Incompatible attribute:
                  - Required org.jetbrains.kotlin.native.target 'linux_x64' and found incompatible value 'ios_arm64'.
              - Other attributes:
                  - Found org.gradle.status 'release' but wasn't required.
                  - Required org.gradle.usage 'kotlin-api' and found compatible value 'kotlin-api'.
                  - Required org.jetbrains.kotlin.platform.type 'native' and found compatible value 'native'.
          - Variant 'iosX64-api' capability me.emig:engineEmi:0.36:
              - Incompatible attribute:
                  - Required org.jetbrains.kotlin.native.target 'linux_x64' and found incompatible value 'ios_x64'.
              - Other attributes:
                  - Found org.gradle.status 'release' but wasn't required.
                  - Required org.gradle.usage 'kotlin-api' and found compatible value 'kotlin-api'.
                  - Required org.jetbrains.kotlin.platform.type 'native' and found compatible value 'native'.
          - Variant 'js-api' capability me.emig:engineEmi:0.36:
              - Incompatible attribute:
                  - Required org.jetbrains.kotlin.platform.type 'native' and found incompatible value 'js'.
              - Other attributes:
                  - Found org.gradle.status 'release' but wasn't required.
                  - Required org.gradle.usage 'kotlin-api' and found compatible value 'kotlin-api'.
                  - Required org.jetbrains.kotlin.native.target 'linux_x64' but no value provided.
          - Variant 'js-runtime' capability me.emig:engineEmi:0.36:
              - Incompatible attributes:
                  - Required org.gradle.usage 'kotlin-api' and found incompatible value 'kotlin-runtime'.
                  - Required org.jetbrains.kotlin.platform.type 'native' and found incompatible value 'js'.
              - Other attributes:
                  - Found org.gradle.status 'release' but wasn't required.
                  - Required org.jetbrains.kotlin.native.target 'linux_x64' but no value provided.
          - Variant 'jvm-api' capability me.emig:engineEmi:0.36:
              - Incompatible attribute:
                  - Required org.jetbrains.kotlin.platform.type 'native' and found incompatible value 'jvm'.
              - Other attributes:
                  - Found org.gradle.libraryelements 'jar' but wasn't required.
                  - Found org.gradle.status 'release' but wasn't required.
                  - Required org.gradle.usage 'kotlin-api' and found compatible value 'java-api'.
                  - Required org.jetbrains.kotlin.native.target 'linux_x64' but no value provided.
          - Variant 'jvm-runtime' capability me.emig:engineEmi:0.36:
              - Incompatible attribute:
                  - Required org.jetbrains.kotlin.platform.type 'native' and found incompatible value 'jvm'.
              - Other attributes:
                  - Found org.gradle.libraryelements 'jar' but wasn't required.
                  - Found org.gradle.status 'release' but wasn't required.
                  - Required org.gradle.usage 'kotlin-api' and found compatible value 'java-runtime'.
                  - Required org.jetbrains.kotlin.native.target 'linux_x64' but no value provided.
          - Variant 'macosX64-api' capability me.emig:engineEmi:0.36:
              - Incompatible attribute:
                  - Required org.jetbrains.kotlin.native.target 'linux_x64' and found incompatible value 'macos_x64'.
              - Other attributes:
                  - Found org.gradle.status 'release' but wasn't required.
                  - Required org.gradle.usage 'kotlin-api' and found compatible value 'kotlin-api'.
                  - Required org.jetbrains.kotlin.platform.type 'native' and found compatible value 'native'.
          - Variant 'metadata-api' capability me.emig:engineEmi:0.36:
              - Incompatible attribute:
                  - Required org.jetbrains.kotlin.platform.type 'native' and found incompatible value 'common'.
              - Other attributes:
                  - Found org.gradle.status 'release' but wasn't required.
                  - Required org.gradle.usage 'kotlin-api' and found compatible value 'kotlin-api'.
                  - Required org.jetbrains.kotlin.native.target 'linux_x64' but no value provided.
          - Variant 'mingwX64-api' capability me.emig:engineEmi:0.36:
              - Incompatible attribute:
                  - Required org.jetbrains.kotlin.native.target 'linux_x64' and found incompatible value 'mingw_x64'.
              - Other attributes:
                  - Found org.gradle.status 'release' but wasn't required.
                  - Required org.gradle.usage 'kotlin-api' and found compatible value 'kotlin-api'.
                  - Required org.jetbrains.kotlin.platform.type 'native' and found compatible value 'native'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
2 actionable tasks: 2 executed
15:48:20: Task execution finished 'runNative'.

```

**Comment by emign** [comment]
War ein Versuch wert. Unix Unterstützung ist experimentell. Am meisten Hoffnung hätte ich mit runJvmOtherThread. Aber im Großen und Ganzen wir das auf Linux immer Gebastel

**Comment by Selemba1000** [comment]
Fehlercode mit Stacktrace:
```
17:55:06: Executing task 'openLocal --stacktrace'...


> Configure project :
Kotlin Multiplatform Projects are an experimental feature.

> Task :compileKotlinJvm UP-TO-DATE
> Task :genResources UP-TO-DATE
> Task :jvmProcessResources UP-TO-DATE
> Task :jvmMainClasses UP-TO-DATE

> Task :runJvmFirstThread
screenWidth: 1366, screenHeight: 768, winX=-1317, winY=-624
VI: native@0x7f5ecc771480, d: native@0x7f5ecc72d770 (com.sun.jna.platform.unix.X11$Display@cc7356ce), w: 0xc00001, glc: native@0x7f5ecc771710
GL_VENDOR: Intel Open Source Technology Center
GL_VERSION: 3.0 Mesa 19.2.8
keysim: 0x41
0.01
OpenglAG: Created program BatchBuilder2D.NoPremultiplied.Tinted with id 1 because contextVersion: -1 != 0
OpenglAG: Created program BatchBuilder2D.Premultiplied.Tinted with id 4 because contextVersion: -1 != 0

> Task :runJvmFirstThread FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runJvmFirstThread'.
> Process 'command '/home/Selemba/InteliJ/ideaIC-2019.3.3/idea-IC-193.6494.35/jbr/bin/java'' finished with non-zero exit value 1

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':runJvmFirstThread'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:166)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:163)
	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:191)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:156)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
	at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
	at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: org.gradle.process.internal.ExecException: Process 'command '/home/Selemba/InteliJ/ideaIC-2019.3.3/idea-IC-193.6494.35/jbr/bin/java'' finished with non-zero exit value 1
	at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:409)
	at org.gradle.process.internal.DefaultJavaExecAction.execute(DefaultJavaExecAction.java:40)
	at org.gradle.api.tasks.JavaExec.exec(JavaExec.java:121)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:49)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:42)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:717)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:684)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$5.run(ExecuteActionsTaskExecuter.java:476)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:461)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:444)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:93)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:237)
	at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:33)
	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)
	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
	at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:58)
	at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:35)
	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:48)
	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:33)
	at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:39)
	at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
	at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
	at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:35)
	at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
	at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:45)
	at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:31)
	at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:208)
	at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:70)
	at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:45)
	at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
	at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:43)
	at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:32)
	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:96)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:89)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:54)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:38)
	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:90)
	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:48)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:69)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:47)
	at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:140)
	... 34 more


* Get more help at https://help.gradle.org

BUILD FAILED in 7s
4 actionable tasks: 1 executed, 3 up-to-date
17:55:14: Task execution finished 'openLocal --stacktrace'.

```
